//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Service_References.ExchangeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExchangeService.IExServiceContract")]
    public interface IExServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExServiceContract/Get", ReplyAction="http://tempuri.org/IExServiceContract/GetResponse")]
        decimal Get(decimal money, string inValue, string outValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExServiceContract/Get", ReplyAction="http://tempuri.org/IExServiceContract/GetResponse")]
        System.Threading.Tasks.Task<decimal> GetAsync(decimal money, string inValue, string outValue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExServiceContractChannel : IExServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExServiceContractClient : System.ServiceModel.ClientBase<IExServiceContract>, IExServiceContract {
        
        public ExServiceContractClient() {
        }
        
        public ExServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal Get(decimal money, string inValue, string outValue) {
            return base.Channel.Get(money, inValue, outValue);
        }
        
        public System.Threading.Tasks.Task<decimal> GetAsync(decimal money, string inValue, string outValue) {
            return base.Channel.GetAsync(money, inValue, outValue);
        }
    }
}
