//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Service_References.WeatherService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherService.IWtServiceContract")]
    public interface IWtServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWtServiceContract/Get", ReplyAction="http://tempuri.org/IWtServiceContract/GetResponse")]
        string Get(string City);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWtServiceContract/Get", ReplyAction="http://tempuri.org/IWtServiceContract/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync(string City);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWtServiceContract/GetWeatherFromOpenWeatherApi", ReplyAction="http://tempuri.org/IWtServiceContract/GetWeatherFromOpenWeatherApiResponse")]
        string GetWeatherFromOpenWeatherApi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWtServiceContract/GetWeatherFromOpenWeatherApi", ReplyAction="http://tempuri.org/IWtServiceContract/GetWeatherFromOpenWeatherApiResponse")]
        System.Threading.Tasks.Task<string> GetWeatherFromOpenWeatherApiAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWtServiceContractChannel : IWtServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WtServiceContractClient : System.ServiceModel.ClientBase<IWtServiceContract>, IWtServiceContract {
        
        public WtServiceContractClient() {
        }
        
        public WtServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WtServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WtServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WtServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get(string City) {
            return base.Channel.Get(City);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(string City) {
            return base.Channel.GetAsync(City);
        }
        
        public string GetWeatherFromOpenWeatherApi() {
            return base.Channel.GetWeatherFromOpenWeatherApi();
        }
        
        public System.Threading.Tasks.Task<string> GetWeatherFromOpenWeatherApiAsync() {
            return base.Channel.GetWeatherFromOpenWeatherApiAsync();
        }
    }
}
