//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.WeatherService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherService.IWeatherServiceContract")]
    public interface IWeatherServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherServiceContract/Get", ReplyAction="http://tempuri.org/IWeatherServiceContract/GetResponse")]
        string Get(string City);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherServiceContract/Get", ReplyAction="http://tempuri.org/IWeatherServiceContract/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync(string City);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherServiceContract/GetWeatherFromOpenWeatherApi", ReplyAction="http://tempuri.org/IWeatherServiceContract/GetWeatherFromOpenWeatherApiResponse")]
        string GetWeatherFromOpenWeatherApi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherServiceContract/GetWeatherFromOpenWeatherApi", ReplyAction="http://tempuri.org/IWeatherServiceContract/GetWeatherFromOpenWeatherApiResponse")]
        System.Threading.Tasks.Task<string> GetWeatherFromOpenWeatherApiAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeatherServiceContractChannel : Client.WeatherService.IWeatherServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherServiceContractClient : System.ServiceModel.ClientBase<Client.WeatherService.IWeatherServiceContract>, Client.WeatherService.IWeatherServiceContract {
        
        public WeatherServiceContractClient() {
        }
        
        public WeatherServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Get(string City) {
            return base.Channel.Get(City);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(string City) {
            return base.Channel.GetAsync(City);
        }
        
        public string GetWeatherFromOpenWeatherApi() {
            return base.Channel.GetWeatherFromOpenWeatherApi();
        }
        
        public System.Threading.Tasks.Task<string> GetWeatherFromOpenWeatherApiAsync() {
            return base.Channel.GetWeatherFromOpenWeatherApiAsync();
        }
    }
}
